##############################################################################
# Copyright (c) 2015, 2016 Ericsson AB and others.
# jonas.bjurel@ericsson.com
# peter.barabas@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dea-base-config-metadata:
  title: 'Deployment Environment Adapter Base configuration'
  # DEA API version supported
  version: '0.4'
  created: 'Fri Jun 10 2016'
  comment: 'Rebased for Fuel 9'
environment:
  net_segment_type: %{network/networking_parameters/segmentation_type}
fuel:
  FUEL_ACCESS:
    %{fuel/FUEL_ACCESS}
wanted_release: %{wanted_release}
settings:
  %{settings}
