##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: mcp-fdio-ha.local
  states:
    - openstack_ha
    - networks
virtual:
  nodes:
    control:
      - kvm01
      - kvm02
      - kvm03
    compute:
      - cmp001
      - cmp002
  # Below values are only used for each node if said node is virtual
  cfg01:
    vcpus: 4
    ram: 6144
  mas01:
    vcpus: 4
    ram: 6144
  # NOTE: We might need to add more RAM here
  kvm01:
    vcpus: 4
    ram: 14336
  kvm02:
    vcpus: 4
    ram: 14336
  kvm03:
    vcpus: 4
    ram: 14336
  cmp001:
    disks: 100G;100G
    vcpus: 4
    ram: 14336
  cmp002:
    disks: 100G;100G
    vcpus: 4
    ram: 14336
