##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: mcp-odl-noha.local
  states:
    - opendaylight
    - openstack_noha
    - neutron_gateway
    - networks
virtual:
  nodes:
    control:
      - ctl01
      - gtw01
      - odl01
    compute:
      - cmp001
      - cmp002
  ctl01:
    ram: 14336
  gtw01:
    vcpus: 2
    ram: 2048
  odl01:
    ram: 6144
  cmp001:
    disks: 100G;100G
  cmp002:
    disks: 100G;100G
