title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for LF POD1

# Adapter to use for this definition
adapter: ipmi

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 00:25:b5:b0:00:ef
  ipmiIp: 172.30.8.69
  ipmiUser: admin
  ipmiPass: octopus
- id: 2
  pxeMac: 00:25:b5:b0:00:cf
  ipmiIp: 172.30.8.78
  ipmiUser: admin
  ipmiPass: octopus
- id: 3
  pxeMac: 00:25:b5:b0:00:8f
  ipmiIp: 172.30.8.68
  ipmiUser: admin
  ipmiPass: octopus
- id: 4
  pxeMac: 00:25:b5:b0:00:6f
  ipmiIp: 172.30.8.77
  ipmiUser: admin
  ipmiPass: octopus
- id: 5
  pxeMac: 00:25:b5:b0:00:4f
  ipmiIp: 172.30.8.67
  ipmiUser: admin
  ipmiPass: octopus
# Adding the Fuel node as node id 6 which may not be correct - please
# adjust as needed.
- id: 6
  libvirtName: fuel-opnfv
  libvirtTemplate: templates/hardware_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 100G