##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.reclass.storage.system.openstack_gateway_single
  - cluster.virtual-mcp-pike-common-noha.infra.config
  - cluster.virtual-mcp-pike-ovs-dpdk-noha
parameters:
  reclass:
    storage:
      node:
        openstack_compute_node01:
          params:
            dpdk0_name: ${_param:opnfv_vm_tertiary_interface}
            dpdk0_pci: '"0000:00:05.0"'
        openstack_compute_node02:
          params:
            dpdk0_name: ${_param:opnfv_vm_tertiary_interface}
            dpdk0_pci: '"0000:00:05.0"'
        openstack_gateway_node01:
          params:
            tenant_address: 10.1.0.110
            external_address: 10.16.0.110
