##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - cluster.baremetal-mcp-ocata-ovs-dpdk-ha.infra
  - cluster.baremetal-mcp-ocata-common.infra.config
parameters:
  reclass:
    storage:
      node:
        openstack_compute_node01:
          params:
            dpdk0_name: enp7s0
            dpdk0_pci: '"0000:07:00.0"'
        openstack_compute_node02:
          params:
            dpdk0_name: enp7s0
            dpdk0_pci: '"0000:07:00.0"'
