dha-pod-config-metadata:
  title: Deployment Hardware Adapter (DHA) for fuel development pipeline - default version
  version: 0.0.4
  created: Jun 14 2016
  comment: Huawei-Ch Fuel9 version

# Adapter to use for this definition
adapter: libvirt

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  libvirtName: controller1
  libvirtTemplate: templates/virtual_environment/vms/controller.xml
- id: 2
  libvirtName: compute1
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 3
  libvirtName: compute2
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 4
  libvirtName: compute3
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 5
  libvirtName: fuel-master
  libvirtTemplate: templates/virtual_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

virtNetConfDir: templates/virtual_environment/networks

disks:
  fuel: 100G
  controller: 100G
  compute: 100G
