##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - service.git.client
  - system.linux.system.single
  - system.linux.system.repo.mcp.salt
  - system.salt.master.api
  - system.salt.master.pkg
  - system.reclass.storage.salt
  - system.salt.minion.ca.salt_master
  - system.mysql.client.single
  - system.reclass.storage.system.openstack_compute_multi
parameters:
  _param:
    openstack_control_node01_hostname: ctl01
    reclass_data_repository: local
    reclass_config_master: ${_param:opnfv_infra_config_pxe_address}
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    single_address: ${_param:opnfv_infra_config_address}
    salt_master_host: 127.0.0.1
    salt_master_base_environment: prd
    salt_minion_ca_host: ${linux:network:fqdn}
    # yamllint disable-line rule:line-length
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  linux:
    network:
      interface:
        dhcp:
          enabled: true
          type: eth
          proto: dhcp
          name: ${_param:opnfv_fn_vm_primary_interface}
        single_int:
          enabled: true
          name: ${_param:opnfv_fn_vm_secondary_interface}
          type: eth
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
        pxe:
          enabled: true
          type: eth
          proto: static
          name: ${_param:opnfv_fn_vm_tertiary_interface}
          address: ${_param:opnfv_infra_config_pxe_address}
          netmask: 255.255.255.0
  salt:
    master:
      file_recv: true
      worker_threads: 4
      command_timeout: 20
  reclass:
    storage:
      data_source:
        engine: local
      node:
        openstack_control_node01:
          name: ${_param:openstack_control_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
            - cluster.${_param:cluster_name}.openstack.control
          params:
            linux_system_codename: xenial
            salt_master_host: ${_param:reclass_config_master}
            single_address: ${_param:openstack_control_node01_address}
        openstack_compute_node01:
          params:
            single_address: ${_param:opnfv_openstack_compute_node01_control_address}
            tenant_address: ${_param:opnfv_openstack_compute_node01_tenant_address}
            external_address: ${_param:opnfv_openstack_compute_node01_external_address}
        openstack_compute_node02:
          params:
            single_address: ${_param:opnfv_openstack_compute_node02_control_address}
            tenant_address: ${_param:opnfv_openstack_compute_node02_tenant_address}
            external_address: ${_param:opnfv_openstack_compute_node02_external_address}
