title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for Ericsson Montreal Lab

# Adapter to use for this definition
adapter: hp

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 14:58:D0:54:7A:D8
  ipmiIp: 10.118.32.198
  ipmiUser: <username>
  ipmiPass: <password>
- id: 2
  pxeMac: 14:58:D0:55:E2:E0
  ipmiIp: 10.118.32.202
  ipmiUser: <username>
  ipmiPass: <password>
- id: 3
  pxeMac: 9C:B6:54:8A:25:C0
  ipmiIp: 10.118.32.213
  ipmiUser: <username>
  ipmiPass: <password>
- id: 4
  pxeMac: 14:58:D0:54:28:80
  ipmiIp: 10.118.32.201
  ipmiUser: <username>
  ipmiPass: <password>
- id: 5
  pxeMac: 14:58:D0:54:E7:88
  ipmiIp: 10.118.32.203
  ipmiUser: <username>
  ipmiPass: <password>
- id: 6
  pxeMac: 14:58:D0:54:7A:28
  ipmiIp: 10.118.32.205
  ipmiUser: <username>
  ipmiPass: <password>
# Adding the Fuel node as node id 7 which may not be correct - please
# adjust as needed.
- id: 7
  libvirtName: fuel-opnfv
  libvirtTemplate: templates/hardware_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 100G