##############################################################################
# Copyright (c) 2015 Ericsson AB and others.
# stefan.k.berg@ericsson.com
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

dea-pod-override-config-metadata:
  title: 'Deployment Environment Adapter POD override for Development Pipeline - Ericsson ELX version'
  version: '0.3'
  created: 'Fri Jun 10 2016'
  comment: 'Rebased for Fuel 9'
environment:
  name: opnfv_virt
interfaces_1:
  ens3:
  - fuelweb_admin
  - storage
  ens4:
  - management
  ens5:
  - private
  ens6:
  - public
interfaces_dpdk:
  ens3:
  - fuelweb_admin
  - storage
  ens4:
  - management
  ens5:
  - private
  - interface_properties:
      dpdk:
        enabled:
          value: true
  ens6:
  - public
interfaces_vlan:
  ens3:
  - fuelweb_admin
  - storage
  ens4:
  - management
  ens5:
  - private
  ens6:
  - public
fuel:
  ADMIN_NETWORK:
    dhcp_pool_end: 10.20.0.254
    dhcp_pool_start: 10.20.0.3
    ipaddress: 10.20.0.2
    netmask: 255.255.255.0
    ssh_network: 10.20.0.0/24
  DNS_DOMAIN: domain.tld
  DNS_SEARCH: domain.tld
  DNS_UPSTREAM: 8.8.8.8, 8.8.4.4
  HOSTNAME: fuel
  NTP1: 0.ubuntu.pool.ntp.org
  NTP2: 1.ubuntu.pool.ntp.org
  NTP3: 2.ubuntu.pool.ntp.org
network:
  networking_parameters:
    base_mac: fa:16:3e:00:00:00
    configuration_template: null
    dns_nameservers:
    - 8.8.8.8
    - 8.8.4.4
    floating_name: admin_floating_net
    floating_ranges:
    - - 172.16.0.130
      - 172.16.0.254
    gre_id_range:
    - 2
    - 65535
    internal_cidr: 192.168.111.0/24
    internal_gateway: 192.168.111.1
    internal_name: admin_internal_net
    net_l23_provider: ovs
    segmentation_type: tun
    vlan_range:
    - 1000
    - 1030
  networks:
  - cidr: 192.168.1.0/24
    gateway: null
    ip_ranges:
    - - 192.168.1.1
      - 192.168.1.254
    meta:
      cidr: 192.168.1.0/24
      configurable: true
      map_priority: 2
      name: storage
      notation: cidr
      render_addr_mask: storage
      render_type: cidr
      use_gateway: false
      vlan_start: 102
    name: storage
    vlan_start: 102
  - cidr: 192.168.0.0/24
    gateway: null
    ip_ranges:
    - - 192.168.0.1
      - 192.168.0.253
    meta:
      cidr: 192.168.0.0/24
      configurable: true
      map_priority: 2
      name: management
      notation: ip_ranges
      render_addr_mask: internal
      render_type: cidr
      use_gateway: false
      vips:
      - haproxy
      - vrouter
      vlan_start: null
    name: management
    vlan_start: null
  - cidr: 192.168.2.0/24
    gateway: null
    ip_ranges:
    - - 192.168.2.1
      - 192.168.2.254
    meta:
      cidr: 192.168.2.0/24
      configurable: true
      map_priority: 2
      name: private
      notation: cidr
      render_addr_mask: null
      render_type: cidr
      seg_type: tun
      use_gateway: false
      vlan_start: 103
    name: private
    vlan_start: 103
  - cidr: 172.16.0.0/24
    gateway: 172.16.0.1
    ip_ranges:
    - - 172.16.0.2
      - 172.16.0.126
    meta:
      cidr: 172.16.0.0/24
      configurable: true
      floating_range_var: floating_ranges
      ip_range:
      - 172.16.0.2
      - 172.16.0.126
      map_priority: 1
      name: public
      notation: ip_ranges
      render_addr_mask: public
      render_type: null
      use_gateway: true
      vips:
      - haproxy
      - vrouter
      vlan_start: null
    name: public
    vlan_start: null
  - cidr: 10.20.0.0/24
    gateway: 10.20.0.2
    ip_ranges:
    - - 10.20.0.3
      - 10.20.0.254
    meta:
      configurable: false
      map_priority: 0
      notation: ip_ranges
      render_addr_mask: null
      render_type: null
      unmovable: true
      use_gateway: true
    name: fuelweb_admin
    vlan_start: null
settings:
  editable:
    external_dns:
      dns_list:
        description: List of upstream DNS servers
        label: DNS list
        max: 3
        regex:
          error: Invalid IP address
          source: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
        type: text_list
        value:
        - 8.8.8.8
        - 8.8.4.4
        weight: 10
      metadata:
        group: network
        label: Host OS DNS Servers
        weight: 30
    external_ntp:
      metadata:
        group: network
        label: Host OS NTP Servers
        weight: 40
      ntp_list:
        description: List of upstream NTP servers
        label: NTP server list
        regex:
          error: Invalid NTP server
          source: ^[a-zA-Z\d]+[-\.\da-zA-Z]*$
        type: text_list
        value:
        - 0.ubuntu.pool.ntp.org
        - 1.ubuntu.pool.ntp.org
        - 2.ubuntu.pool.ntp.org
        weight: 10
    syslog:
      metadata:
        enabled: false
        group: logging
        label: Syslog
        toggleable: true
        weight: 50
      syslog_port:
        description: Remote syslog port
        label: Port
        regex:
          error: Invalid syslog port
          source: ^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$
        type: text
        value: '514'
        weight: 20
      syslog_server:
        description: Remote syslog hostname
        label: Hostname
        regex:
          error: Invalid hostname
          source: ^[a-zA-Z\d]+[-\.\da-zA-Z]*$
        type: text
        value: ''
        weight: 10
      syslog_transport:
        label: Syslog transport protocol
        type: radio
        value: tcp
        values:
        - data: udp
          description: ''
          label: UDP
        - data: tcp
          description: ''
          label: TCP
        weight: 30

