title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for OPNFV BOX

# Adapter to use for this definition
adapter: amt

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: b8:ae:ed:76:4d:a4
  amtIp: <amt_ip>
  amtUser: <username>
  amtPass: <password>
- id: 2
  pxeMac: b8:ae:ed:76:4d:94
  amtIp: <amt_ip>
  amtUser: <username>
  amtPass: <password>
- id: 3
  pxeMac: b8:ae:ed:76:4c:eb
  amtIp: <amt_ip>
  amtUser: <username>
  amtPass: <password>
- id: 4
  pxeMac: b8:ae:ed:76:37:62
  amtIp: <amt_ip>
  amtUser: <username>
  amtPass: <password>
- id: 5
  pxeMac: b8:ae:ed:76:4d:95
  amtIp: <amt_ip>
  amtUser: <username>
  amtPass: <password>
# Adding the Fuel node as node id 6 which may not be correct - please
# adjust as needed.
- id: 6
  libvirtName: fuel-opnfv
  libvirtTemplate: templates/hardware_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 100G