##############################################################################
# Copyright (c) 2015 Ericsson AB and others.
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

############################################################################### # Description:
# This .yaml configuration file defines the configuration of the fuel
# deployment and is passed as an argument to deploy.sh
# eg. deploy.sh -c https://artifact.opnfv.org/fuel/config
# This will make build.sh fetch this configuration file and configure the
# deployment accordingly.
# After the deployment, a copy of this file gets uploaded to fuel:
# /root/deploy-config.yaml, as well as the sha-1 sum of this file:
# /root/deploy-config.sha1
##############################################################################

##############################################################################
# deployment configuration meta-data
deployment-scenario-metadata:
   title: OpenStack-only, No-HA deployment
   version: 0.0.1
   created: Jul 13 2016
   comment: Fuel OpenStack-only, No-HA deployment rebased with Fuel8

##############################################################################
# Stack extentions are opnfv added value features in form of a fuel-plugin
# plug-ins listed below will be enabled and configured according to the
# <module-config-base-uri>/<module-config-name>_<module-config-version>.yaml
# It does so by copying the config file to the local plugin config directory
stack-extensions:

##############################################################################
# By editing the override-config sections below, you can override arbitrary
# configuration name-space settings

dea-override-config:
  settings:
    editable:
      additional_components:
        ceilometer:
          description: If selected, Ceilometer and Aodh components will be installed
          label: Install Ceilometer and Aodh
          type: checkbox
          value: false
          weight: 60
      storage:
        volumes_ceph:
          value: false
        volumes_lvm:
          value: true
  environment:
    mode: noha
    net_segment_type: vlan
    name: opnfv-noha-vlan-virt-minimal
  nodes:
  - id: 1
    interfaces: interfaces_1
    role: controller
    transformations: transformations_1
  - id: 2
    interfaces: interfaces_1
    role: compute,cinder
    transformations: transformations_1

dha-override-config:
#  disks:
#    contrail: 500G

##############################################################################
# The verification pipeline may populate the section below with arbitrary
# testing information, which post deploy can be retreived from the fuel master:
# /root/deploy-config.yaml
test:
