##############################################################################
# Copyright (c) 2017 Intel Corp. and others.
# navyax.bathula@intel.com,mpolenchuk@mirantis.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

###############################################################################
# Description:
# This .yaml configuration file defines the configuration of the fuel
# deployment and is passed as an argument to deploy.sh
# eg. deploy.sh -c https://artifact.opnfv.org/fuel/config
# This will make build.sh fetch this configuration file and configure the
# deployment accordingly.
# After the deployment, a copy of this file gets uploaded to fuel:
# /root/deploy-config.yaml, as well as the sha-1 sum of this file:
# /root/deploy-config.sha1
##############################################################################

##############################################################################
# deployment configuration meta-data
deployment-scenario-metadata:
   title: NFV KVM OVS-DPDK and Barometer No-HA deployment
   version: 0.0.1
   created: Feb 16 2017
   comment: NFV KVM OVS-DPDK and Barometer

##############################################################################
# Stack extentions are opnfv added value features in form of a fuel-plugin
# plug-ins listed below will be enabled and configured according to the
# <module-config-base-uri>/<module-config-name>_<module-config-version>.yaml
# It does so by copying the config file to the local plugin config directory
stack-extensions:
   - module: fuel-plugin-kvm
     module-config-name: fuel-nfvkvm
     module-config-version: 1.0.0
     module-config-override:
       # Module config overrides
   - module: fuel-plugin-collectd-ceilometer
     module-config-name: fuel-barometer
     module-config-version: 1.0.0
     module-config-override:
       # Module config overrides

##############################################################################
# By editing the override-config sections below, you can override arbitrary
# configuration name-space settings
dea-override-config:
  fuel:
    FEATURE_GROUPS:
    - experimental
  environment:
    net_segment_type: vlan
  nodes:
  - id: 1
    interfaces: interfaces_vlan
    role: mongo,controller
  - id: 2
    interfaces: interfaces_dpdk
    role: ceph-osd,compute
    attributes: attributes_1
  - id: 3
    interfaces: interfaces_dpdk
    role: ceph-osd,compute
    attributes: attributes_1
  - id: 4
    interfaces: interfaces_dpdk
    role: ceph-osd,compute
    attributes: attributes_1

  attributes_1:
    hugepages:
      dpdk:
        value: 1024
      nova:
        value:
          '2048': 1024

  network:
    networking_parameters:
      segmentation_type: vlan
    networks:
    - cidr: null
      gateway: null
      ip_ranges: []
      meta:
        configurable: false
        map_priority: 2
        name: private
        neutron_vlan_range: true
        notation: null
        render_addr_mask: null
        render_type: null
        seg_type: vlan
        use_gateway: false
        vlan_start: null
      name: private
      vlan_start: null

  settings:
    editable:
      storage:
        ephemeral_ceph:
          description: Configures Nova to store ephemeral volumes in RBD. This works
            best if Ceph is enabled for volumes and images, too. Enables live migration
            of all types of Ceph backed VMs (without this option, live migration will
            only work with VMs launched from Cinder volumes).
          label: Ceph RBD for ephemeral volumes (Nova)
          type: checkbox
          value: true
          weight: 75
        images_ceph:
          description: Configures Glance to use the Ceph RBD backend to store images.
            If enabled, this option will prevent Swift from installing.
          label: Ceph RBD for images (Glance)
          restrictions:
          - settings:storage.images_vcenter.value == true: Only one Glance backend could
              be selected.
          type: checkbox
          value: true
          weight: 30

dha-override-config:
#  disks:
#    contrail: 500G

##############################################################################
# The verification pipeline may populate the section below with arbitrary
# testing information, which post deploy can be retreived from the fuel master:
# /root/deploy-config.yaml
test:
