##############################################################################
# Copyright (c) 2015 Ericsson AB and others.
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

############################################################################### # Description:
# This .yaml configuration file defines the configuration of the fuel
# deployment and is passed as an argument to deploy.sh
# eg. deploy.sh -c https://artifact.opnfv.org/fuel/config
# This will make build.sh fetch this configuration file and configure the
# deployment accordingly.
# After the deployment, a copy of this file gets uploaded to fuel:
# /root/deploy-config.yaml, as well as the sha-1 sum of this file:
# /root/deploy-config.sha1
##############################################################################

##############################################################################
# deployment configuration meta-data
deployment-scenario-metadata:
   title: ODL HA BGPVPN deployment
   version: 1.0.0
   created: 29.06.2016
   comment: Fuel ODL No HA with BGPVPN, Ceph, Ceilometer and Heat Rebased for Fuel10

##############################################################################
# Stack extentions are opnfv added value features in form of a fuel-plugin
# plug-ins listed below will be enabled and configured according to the
# <module-config-base-uri>/<module-config-name>_<module-config-version>.yaml
# It does so by copying the config file to the local plugin config directory
stack-extensions:
  - module: opendaylight
    module-config-name: fuel-odl
    module-config-version: 1.0.0
    module-config-override:
      metadata:
        versions:
          - enable_bgpvpn:
              value: true
            metadata:
              plugin_version: 1.0.0

  - module: bgpvpn
    module-config-name: fuel-bgpvpn
    module-config-version: 1.0.0

##############################################################################
# By editing the override-config sections below, you can override arbitrary
# configuration name-space settings
dea-override-config:

  nodes:
  - id: 1
    interfaces: interfaces_1
    role: mongo,controller
  - id: 2
    interfaces: interfaces_1
    role: ceph-osd,opendaylight
  - id: 3
    interfaces: interfaces_1
    role: ceph-osd,compute
  - id: 4
    interfaces: interfaces_1
    role: ceph-osd,compute

dha-override-config:
#  disks:
#    contrail: 500G

##############################################################################
# The verification pipeline may populate the section below with arbitrary
# testing information, which post deploy can be retreived from the fuel master:
# /root/deploy-config.yaml
test:
