##############################################################################
# Copyright (c) 2015 Ericsson AB and others.
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

##############################################################################
# Description:
# This configuration file defines translation between a short deployment
# scenario name and an actual deployment scenario configuration file
#
# Short deployment scenario names are aligned between installer, test, and
# releng projects according to below pattern.
#   os-[controller]-[feature]-[mode](-[optionalparameter])
#
# Please note that the mechanism to get the details regarding the scenarios
# is different currently which needs to be aligned as well.
##############################################################################

##############################################################################
# Short scenario name convention to be followed:
# os-<controller>-<feature>-<mode>[-<optional-parameter>]
# controler: nosdn|odl|onos|ocl|...
# feaure: nofeature | [vlan]_[kvm]_[ovs]_[vlan]_....
# mode: ha|noha
##############################################################################

os-nosdn-nofeature-ha:
  configfile: ha_heat_ceilometer_scenario.yaml

os-nosdn-nofeature-noha:
  configfile: no-ha_heat_ceilometer_scenario.yaml

os-odl_l3-nofeature-ha:
  configfile: ha_odl-l3_heat_ceilometer_scenario.yaml

os-odl_l3-nofeature-noha:
  configfile: no-ha_odl-l3_heat_ceilometer_scenario.yaml

os-odl_l2-nofeature-ha:
  configfile: ha_odl-l2_heat_ceilometer_scenario.yaml

os-odl_l2-nofeature-noha:
  configfile: no-ha_odl-l2_heat_ceilometer_scenario.yaml

os-onos-nofeature-ha:
  configfile: ha_onos_nofeature_heat_ceilometer_scenario.yaml

os-onos-nofeature-noha:
  configfile: no-ha_onos_nofeature_heat_ceilometer_scenario.yaml

os-onos-sfc-ha:
  configfile: ha_onos_sfc_heat_ceilometer_scenario.yaml 

os-onos-sfc-noha:
  configfile: no-ha_onos_sfc_heat_ceilometer_scenario.yaml

os-nosdn-kvm-ha:
  configfile: ha_nfv-kvm_heat_ceilometer_scenario.yaml

os-nosdn-kvm-noha:
  configfile: no-ha_nfv-kvm_heat_ceilometer_scenario.yaml

os-nosdn-ovs-ha:
  configfile: ha_nfv-ovs_heat_ceilometer_scenario.yaml

os-nosdn-ovs-noha:
  configfile: no-ha_nfv-ovs_heat_ceilometer_scenario.yaml

os-odl_l2-bgpvpn-ha:
  configfile: ha_odl-bgpvpn_scenario.yaml

os-odl_l2-bgpvpn-noha:
  configfile: no-ha_odl-bgpvpn_scenario.yaml

os-odl_l2-sfc-ha:
  configfile: ha_odl-l2_sfc_heat_ceilometer_scenario.yaml

os-odl_l2-sfc-noha:
  configfile: no-ha_odl-l2_sfc_heat_ceilometer_scenario.yaml

os-nosdn-kvm_ovs_dpdk-ha:
  configfile: ha_nfv-kvm_nfv-ovs-dpdk_heat_ceilometer_scenario.yaml

os-nosdn-kvm_ovs_dpdk-noha:
  configfile: no-ha_nfv-kvm_nfv-ovs-dpdk_heat_ceilometer_scenario.yaml

os-nosdn-kvm_ovs_dpdk_bar-ha:
  configfile: ha_nfv-kvm_nfv-ovs-dpdk-bar_heat_ceilometer_scenario.yaml

os-nosdn-kvm_ovs_dpdk_bar-noha:
  configfile: no-ha_nfv-kvm_nfv-ovs-dpdk-bar_heat_ceilometer_scenario.yaml
