classes:
- cluster.virtual-mcp-ocata-common.infra.config
- cluster.virtual-mcp-ocata-ovs-dpdk
parameters:
  reclass:
    storage:
      node:
        openstack_compute_node01:
          params:
            dpdk0_name: ${_param:opnfv_fn_vm_tertiary_interface}
            dpdk0_pci: '"0000:00:05.0"'
        openstack_compute_node02:
          params:
            dpdk0_name: ${_param:opnfv_fn_vm_tertiary_interface}
            dpdk0_pci: '"0000:00:05.0"'
