title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for Virtual Environment

# Adapter to use for this definition
adapter: libvirt

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  libvirtName: controller1
  libvirtTemplate: templates/virtual_environment/vms/controller.xml
- id: 2
  libvirtName: controller2
  libvirtTemplate: templates/virtual_environment/vms/controller.xml
- id: 3
  libvirtName: controller3
  libvirtTemplate: templates/virtual_environment/vms/controller.xml
- id: 4
  libvirtName: compute1
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 5
  libvirtName: compute2
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 6
  libvirtName: compute3
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 7
  libvirtName: fuel-master
  libvirtTemplate: templates/virtual_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

virtNetConfDir: templates/virtual_environment/networks

disks:
  fuel: 100G
  controller: 60G
  compute: 50G