---
- name: install controller-related neutron packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - neutron-server
    - neutron-plugin-ml2

- name: generate neutron controll service list
  shell: echo {{ item }} >> /opt/service
  with_items:
    - neutron-server
    - neutron-plugin-ml2

- name: get tenant id to fill neutron.conf
  shell: keystone --os-token={{ ADMIN_TOKEN }} --os-endpoint=http://{{ HA_VIP }}:35357/v2.0 tenant-get service | grep id | awk '{print $4}'
  register: NOVA_ADMIN_TENANT_ID

- name: update neutron conf
  template: src=neutron.conf dest=/etc/neutron/neutron.conf backup=yes
  notify:
    - restart neutron-server

- name: update ml2 plugin conf
  template: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini backup=yes
  notify:
    - restart neutron-server

- meta: flush_handlers

