##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - cluster.baremetal-mcp-pike-common-ha.infra.config
  - cluster.baremetal-mcp-pike-ovs-novcp-ha.infra
parameters:
  reclass:
    storage:
      node:
        openstack_control_node01:  # openstack_proxy_node01
          params:
            external_address: ${_param:openstack_proxy_node01_address}
        openstack_control_node02:  # no proxy role
          params:
            external_address: 0.0.0.0
        openstack_control_node03:  # openstack_proxy_node02
          params:
            external_address: ${_param:openstack_proxy_node02_address}
