title: Deployment Hardware Adapter (DHA)
# DHA API version supported
version:
created:
comment: Config for LF POD2 and Opendaylight

# Adapter to use for this definition
adapter: ipmi

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 00:25:b5:a0:00:2a
  ipmiIp: 172.30.8.75
  ipmiUser: admin
  ipmiPass: octopus
- id: 2
  pxeMac: 00:25:b5:a0:00:3a
  ipmiIp: 172.30.8.65
  ipmiUser: admin
  ipmiPass: octopus
- id: 3
  pxeMac: 00:25:b5:a0:00:4a
  ipmiIp: 172.30.8.74
  ipmiUser: admin
  ipmiPass: octopus
- id: 4
  pxeMac: 00:25:b5:a0:00:5a
  ipmiIp: 172.30.8.73
  ipmiUser: admin
  ipmiPass: octopus
- id: 5
  pxeMac: 00:25:b5:a0:00:6a
  ipmiIp: 172.30.8.72
  ipmiUser: admin
  ipmiPass: octopus
# Adding the Fuel node as node id 6 which may not be correct - please
# adjust as needed.
- id: 6
  libvirtName: fuel-opnfv
  libvirtTemplate: templates/hardware_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 100G