cluster:
  domain: virtual-mcp-ocata-ovs.local
  states:
    - openstack
    - neutron_compute
    - networks
virtual:
  nodes:
    - cfg01
    - ctl01
    - cmp01
    - cmp02
    - gtw01
  ctl01:
    vcpus: 4
    ram: 14336
  gtw01:
    ram: 2048
