##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: virtual-mcp-pike-odl-noha.local
  states:
    - opendaylight
    - openstack_noha
    - neutron_gateway
    - networks
virtual:
  nodes:
    - cfg01
    - ctl01
    - cmp01
    - cmp02
    - gtw01
    - odl01
  ctl01:
    vcpus: 4
    ram: 14336
  gtw01:
    ram: 2048
  odl01:
    vcpus: 4
    ram: 5120
