cluster:
  domain: virtual-mcp-ocata-odl.local
  states:
    - opendaylight
    - openstack
    - networks
virtual:
  nodes:
    - cfg01
    - ctl01
    - cmp01
    - cmp02
    - gtw01
    - odl01
  ctl01:
    vcpus: 4
    ram: 14336
  gtw01:
    ram: 2048
  odl01:
    vcpus: 4
    ram: 5120
