---
cluster:
  domain: baremetal-mcp-ocata-ovs-dpdk-ha.local
  states:
    - maas
    - dpdk
    - openstack_ha
    - neutron_compute
    - networks
virtual:
  nodes:
    - cfg01
    - mas01
  cfg01:
    vcpus: 4
    ram: 6144
  mas01:
    vcpus: 4
    ram: 6144
