##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: baremetal-mcp-pike-odl-ha.local
  states:
    - maas
    - baremetal_init
    - virtual_control_plane
    - opendaylight
    - openstack_ha
    - networks
virtual:
  nodes:
    - cfg01
    - mas01
  cfg01:
    vcpus: 4
    ram: 6144
  mas01:
    vcpus: 4
    ram: 6144
