cluster:
  domain: baremetal-mcp-ocata-odl-ha.local
  states:
    - maas
    - virtual_control_plane
    - opendaylight
    - openstack_ha
    - networks
virtual:
  nodes:
    - cfg01
    - mas01
  mas01:
    vcpus: 4
    ram: 16384
