##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.reclass.storage.system.opendaylight_control_single
  - cluster.mcp-common-ha.infra.config
  - cluster.mcp-odl-ha.infra
  - cluster.all-mcp-arch-common.infra.config_pdf
parameters:
  reclass:
    storage:
      node:
        opendaylight_control_node01:
          classes:
            - cluster.${_param:cluster_name}.opendaylight.control
          params:
            linux_system_codename: xenial
            single_address: ${_param:opendaylight_server_node01_single_address}
